version: '4'
services:
  # Add the Flask application Service
  backend:
  # Location of the Flask Application dockerfile
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - frontend-nginx
    ports:
      # Flask application Host port: Flask Container port
      - "5000"



  # nginx service
  frontend-nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
