version: '4'
services:
  # Add the Flask application Service
  backend:
  # Location of the Flask Application dockerfile
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - frontend
    ports:
      # Flask application Host port: Flask Container port
      - "5000"


  # Angular application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend"
    ports:
      # Port for the angular app
      - "4200:4200"

  # nginx service
  nginx:
  # The official nginx Docker from Docker Hub. For building the nginx container
    image: nginx:latest
    volumes:
    # Volume for the nginx Docker container
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    # The nginx service depends on the Flask application service (It will link the Flask web application and Nginx Load balancer)
    depends_on:
      - backend
      - frontend
    # ports for the nginx application service
    ports:
    # Port for the Nginx load balancer
      - "80:80"